//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SunnyvaleNailBar.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AUTONUM
    {
        public string NUMBERNAME { get; set; }
        public string CURRENTPREFIX { get; set; }
        public decimal DIGITSWIDTH { get; set; }
        public decimal CURRENTDIGITS { get; set; }
        public decimal VALUEINTERVAL { get; set; }
        public decimal MINVALUE { get; set; }
        public decimal MAXVALUE { get; set; }
    }
}
